apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: apache-latest-secret-provider
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/internet-ctf/secrets/apache-latest-flag/versions/1"
        path: "flag.txt"
