apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-apache-latest
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: /chroot/flag
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: apache-latest-secret-provider
  healthcheck:
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:0ee21473a157ff2c8d979bc14db3f9d3ce9174d74429c0467c62146bc6ed6162
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:4dfb6e3ea5c505fbd858991a6a036d21b2532eee828d9069229f84fc871ce76f
