apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-mlflow
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: "/chroot/flag"
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: mlflow-exposed-auth-bypass-secret-provider
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:50723cc1a0bb193511d9c5e1c64f8d5877a498eac431efa7a7e31044ba9029be
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:0c0682949eba94537b2bab68a8d978be27ebe06f51dbf08d67fc5cf38932ebf0
