apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-mlflow
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: "/chroot/flag"
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: mlflow-exposed-auth-bypass-secret-provider
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:888f217b8fbff7137b960f19d71ad0fac5dfa032f88d1e8d1a2515d4e0ba9827
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:fd4f45fa89f7ca465715dc9de900a7206e381643e20dc6c70b2d1ee5e3ecfdf1
