apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-apache
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: /flag
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: apache-path-traversal-secret-provider
  healthcheck:
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:e7eff8dbe8a9512bfd8c3a85c481272ef455eaa24ab262839f58ed840114064d
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:5fe79e9b728fe8583b8b819da447e5558e6b91f2e49e2f6e5ccd4b84b1153d9f
