apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-apache
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: /chroot/flag
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: apache-path-traversal-secret-provider
  healthcheck:
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:25b42619c9160e014bea3bee2ef53cd95cebff6c662fb772a723d941685e4812
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:a69a5282c51260840819977ebad7fb5097cb20dac7790fef7099a23d6cded060
